#!/bin/zsh

#Function test
usage () {
   echo "$0 <link> <from> <to> <output>"
   exit 1
}

[[ $# -lt 4 ]] && usage
[[ $1 =~ ^https://www\.youtube\.com ]] || [[ $1 =~ ^https://youtu\.be ]] || usage
[[ $2 =~ ^[0-9]\{1,\}\.[0-9]\{2\}$ ]] || usage
[[ $3 =~ ^[0-9]\{1,\}\.[0-9]\{2\}$ ]] || usage
[[ $4 =~ \.webm$ ]] || [[ $4 =~ \.mp4$ ]] || usage

FILENAME=$(yt-dlp "$1" --print title)
TMPFILE="/tmp/$FILENAME.webm"
CLIP="/tmp/$4"
#Convert times from ss.ms to HH:MM:SS.ms
FROM=$(date -u "+%T.%2N" -d @"$2")
TO=$(date -u "+%T.%2N" -d @"$3")
yt-dlp "$1" --downloader aria2c -o "$TMPFILE"
ffmpeg -i "$TMPFILE" -ss "$FROM" -to "$TO" "$CLIP"
mv "$CLIP" "$PWD/$4"
herbe "Save source video?" && mv "$TMPFILE" "$PWD/$FILENAME.webm"
