#!/bin/sh
touch /tmp/screenshot.png
import png:/tmp/screenshot.png
NAME=$(date +%s)
PIC=$(pyupload --host=catbox /tmp/screenshot.png)
echo "$PIC" | grep -o "\<https.\+png$" | xclip -r -selection clipboard
LINK=$(xclip -selection clipboard -o)
herbe "Open screenshot" && xdg-open "$LINK"
if herbe "Save locally?"; then
	mv /tmp/screenshot.png /bigdrive/pics/screenshot/S$NAME.png
else
	rm /tmp/screenshot.png
fi
